#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-spatstat
Version  : 1.55.1
Release  : 10
URL      : https://cran.r-project.org/src/contrib/spatstat_1.55-1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/spatstat_1.55-1.tar.gz
Summary  : Spatial Point Pattern Analysis, Model-Fitting, Simulation, Tests
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-spatstat-lib
Requires: R-RandomFields
Requires: R-abind
Requires: R-deldir
Requires: R-goftest
Requires: R-locfit
Requires: R-polyclip
Requires: R-spatstat.data
Requires: R-tensor
BuildRequires : R-RandomFields
BuildRequires : R-abind
BuildRequires : R-deldir
BuildRequires : R-goftest
BuildRequires : R-locfit
BuildRequires : R-polyclip
BuildRequires : R-spatstat.data
BuildRequires : R-tensor
BuildRequires : clr-R-helpers

%description
Contains over 2000 functions for plotting spatial data, exploratory data analysis, model-fitting, simulation, spatial sampling, model diagnostics, and formal inference. 
	Data types include point patterns, line segment patterns, spatial windows, pixel images, tessellations, and linear networks. 
	Exploratory methods include quadrat counts, K-functions and their simulation envelopes, nearest neighbour distance and empty space statistics, Fry plots, pair correlation function, kernel smoothed intensity, relative risk estimation with cross-validated bandwidth selection, mark correlation functions, segregation indices, mark dependence diagnostics, and kernel estimates of covariate effects. Formal hypothesis tests of random pattern (chi-squared, Kolmogorov-Smirnov, Monte Carlo, Diggle-Cressie-Loosmore-Ford, Dao-Genton, two-stage Monte Carlo) and tests for covariate effects (Cox-Berman-Waller-Lawson, Kolmogorov-Smirnov, ANOVA) are also supported.
	Parametric models can be fitted to point pattern data using the functions ppm(), kppm(), slrm(), dppm() similar to glm(). Types of models include Poisson, Gibbs and Cox point processes, Neyman-Scott cluster processes, and determinantal point processes. Models may involve dependence on covariates, inter-point interaction, cluster formation and dependence on marks. Models are fitted by maximum likelihood, logistic regression, minimum contrast, and composite likelihood methods. 
	A model can be fitted to a list of point patterns (replicated point pattern data) using the function mppm(). The model can include random effects and fixed effects depending on the experimental design, in addition to all the features listed above.
	Fitted point process models can be simulated, automatically. Formal hypothesis tests of a fitted model are supported (likelihood ratio test, analysis of deviance, Monte Carlo tests) along with basic tools for model selection (stepwise(), AIC()). Tools for validating the fitted model include simulation envelopes, residuals, residual plots and Q-Q plots, leverage and influence diagnostics, partial residuals, and added variable plots.

%package lib
Summary: lib components for the R-spatstat package.
Group: Libraries

%description lib
lib components for the R-spatstat package.


%prep
%setup -q -c -n spatstat

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523747436

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1523747436
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library spatstat
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library spatstat
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library spatstat
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library spatstat|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/spatstat/CITATION
/usr/lib64/R/library/spatstat/DESCRIPTION
/usr/lib64/R/library/spatstat/INDEX
/usr/lib64/R/library/spatstat/Meta/Rd.rds
/usr/lib64/R/library/spatstat/Meta/demo.rds
/usr/lib64/R/library/spatstat/Meta/features.rds
/usr/lib64/R/library/spatstat/Meta/hsearch.rds
/usr/lib64/R/library/spatstat/Meta/links.rds
/usr/lib64/R/library/spatstat/Meta/nsInfo.rds
/usr/lib64/R/library/spatstat/Meta/package.rds
/usr/lib64/R/library/spatstat/Meta/vignette.rds
/usr/lib64/R/library/spatstat/NAMESPACE
/usr/lib64/R/library/spatstat/NEWS
/usr/lib64/R/library/spatstat/R/spatstat
/usr/lib64/R/library/spatstat/R/spatstat.rdb
/usr/lib64/R/library/spatstat/R/spatstat.rdx
/usr/lib64/R/library/spatstat/R/sysdata.rdb
/usr/lib64/R/library/spatstat/R/sysdata.rdx
/usr/lib64/R/library/spatstat/demo/data.R
/usr/lib64/R/library/spatstat/demo/diagnose.R
/usr/lib64/R/library/spatstat/demo/spatstat.R
/usr/lib64/R/library/spatstat/demo/sumfun.R
/usr/lib64/R/library/spatstat/doc/BEGINNER.txt
/usr/lib64/R/library/spatstat/doc/Nickname.txt
/usr/lib64/R/library/spatstat/doc/datasets.R
/usr/lib64/R/library/spatstat/doc/datasets.Rnw
/usr/lib64/R/library/spatstat/doc/datasets.pdf
/usr/lib64/R/library/spatstat/doc/getstart.R
/usr/lib64/R/library/spatstat/doc/getstart.Rnw
/usr/lib64/R/library/spatstat/doc/getstart.pdf
/usr/lib64/R/library/spatstat/doc/index.html
/usr/lib64/R/library/spatstat/doc/packagesizes.txt
/usr/lib64/R/library/spatstat/doc/replicated.R
/usr/lib64/R/library/spatstat/doc/replicated.Rnw
/usr/lib64/R/library/spatstat/doc/replicated.pdf
/usr/lib64/R/library/spatstat/doc/shapefiles.R
/usr/lib64/R/library/spatstat/doc/shapefiles.Rnw
/usr/lib64/R/library/spatstat/doc/shapefiles.pdf
/usr/lib64/R/library/spatstat/doc/spatstatlocalsize.txt
/usr/lib64/R/library/spatstat/doc/updates.R
/usr/lib64/R/library/spatstat/doc/updates.Rnw
/usr/lib64/R/library/spatstat/doc/updates.pdf
/usr/lib64/R/library/spatstat/help/AnIndex
/usr/lib64/R/library/spatstat/help/aliases.rds
/usr/lib64/R/library/spatstat/help/macros/defns.Rd
/usr/lib64/R/library/spatstat/help/paths.rds
/usr/lib64/R/library/spatstat/help/spatstat.rdb
/usr/lib64/R/library/spatstat/help/spatstat.rdx
/usr/lib64/R/library/spatstat/html/00Index.html
/usr/lib64/R/library/spatstat/html/R.css
/usr/lib64/R/library/spatstat/libs/symbols.rds
/usr/lib64/R/library/spatstat/ratfor/Makefile
/usr/lib64/R/library/spatstat/ratfor/dppll.r
/usr/lib64/R/library/spatstat/ratfor/inxypOld.r

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/spatstat/libs/spatstat.so
/usr/lib64/R/library/spatstat/libs/spatstat.so.avx2
/usr/lib64/R/library/spatstat/libs/spatstat.so.avx512
